## Датасет собран из базы данных переписи 1994 года и содержит данные о доходах.
### Информация о данных:
* age: continuous.
* workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
* fnlwgt: continuous.
* education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, * Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
* education-num: continuous.
* marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
* occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
* relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
* race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
* sex: Female, Male.
* capital-gain: continuous.
* capital-loss: continuous.
* hours-per-week: continuous.
* native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
* salary: >50K,<=50K

## Проведите анализ данных при помощи Pandas выполнив поставленные задачи.
####

In [1]:
import pandas as pd

In [2]:
# загружаем датасет
data = pd.read_csv("./data/adult.data.csv")
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. Посчитайте, сколько мужчин и женщин (признак *sex*) представлено в этом датасете**

In [6]:
# your code
data["sex"].value_counts()

sex
Male      21790
Female    10771
Name: count, dtype: int64

**2. Каков средний возраст мужчин (признак *age*) по всему датасету?**

In [13]:
# your code
data[data["sex"]=="Male"]["age"].mean()

np.float64(39.43354749885268)

**3. Какова доля граждан Соединенных Штатов (признак *native-country*)?**

In [19]:
# your code
data["native-country"].value_counts(normalize=True)["United-States"]

np.float64(0.895857006848684)

**4-5. Рассчитайте среднее значение и среднеквадратичное отклонение возраста тех, кто получает более 50K в год (признак *salary*) и тех, кто получает менее 50K в год**

In [26]:
# your code
age_above = data[data["salary"] != "<=50K"].age
age_below = data[data["salary"] == "<=50K"].age

print("Те, кто получает больше. Mean: ",age_above.mean()," Std: ",age_above.std())
print("Те, кто получает меньше. Mean: ",age_below.mean()," Std: ",age_below.std())

Те, кто получает больше. Mean:  36.78373786407767  Std:  14.02008849082488
Те, кто получает меньше. Mean:  44.24984058155847  Std:  10.519027719851826

**6. Правда ли, что люди, которые получают больше 50k, имеют минимум высшее образование? (признак *education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* или *Doctorate*)**

In [68]:
# your code
data[data["salary"] == ">50K"]["education"].isin(["Bachelors", "Prof-school", "Assoc-acdm", "Assoc-voc", "Masters" "Doctorate"]).all()

np.False_

**7. Выведите статистику возраста для каждой расы (признак *race*) и каждого пола. Используйте *groupby* и *describe*. Найдите таким образом максимальный возраст мужчин расы *Asian-Pac-Islander*.**

In [56]:
# your code
data.groupby(["race","sex"]).describe()["age"]

                             count       mean        std   min   25%   50%  \
race               sex
Amer-Indian-Eskimo Female    119.0  37.117647  13.114991  17.0  27.0  36.0
                   Male      192.0  37.208333  12.049563  17.0  28.0  35.0
Asian-Pac-Islander Female    346.0  35.089595  12.300845  17.0  25.0  33.0
                   Male      693.0  39.073593  12.883944  18.0  29.0  37.0
Black              Female   1555.0  37.854019  12.637197  17.0  28.0  37.0
                   Male     1569.0  37.682600  12.882612  17.0  27.0  36.0
Other              Female    109.0  31.678899  11.631599  17.0  23.0  29.0
                   Male      162.0  34.654321  11.355531  17.0  26.0  32.0
White              Female   8642.0  36.811618  14.329093  17.0  25.0  35.0
                   Male    19174.0  39.652498  13.436029  17.0  29.0  38.0

                             75%   max
race               sex
Amer-Indian-Eskimo Female  46.00  80.0
                   Male    45.00  82.0
Asian-Pac-Islander Female  43.75  75.0
                   Male    46.00  90.0
Black              Female  46.00  90.0
                   Male    46.00  90.0
Other              Female  39.00  74.0
                   Male    42.00  77.0
White              Female  46.00  90.0
                   Male    49.00  90.0

In [62]:
data.groupby(["race","sex"]).describe()["age"]["max"]["Asian-Pac-Islander"]["Male"]

np.float64(90.0)

**8. Среди кого больше доля зарабатывающих много (>50K): среди женатых или холостых мужчин (признак *marital-status*)? Женатыми считаем тех, у кого *marital-status* начинается с *Married* (Married-civ-spouse, Married-spouse-absent или Married-AF-spouse), остальных считаем холостыми.**

In [71]:
# your code
married = data[data["marital-status"].isin(["Married-civ-spouse","Married-spouse-absent", "Married-AF-spouse"])]
not_married = data[~data["marital-status"].isin(["Married-civ-spouse","Married-spouse-absent", "Married-AF-spouse"])]

In [77]:
married["salary"].value_counts(normalize=True)[">50K"] > not_married["salary"].value_counts(normalize=True)[">50K"]

np.True_

**9. Какое максимальное число часов человек работает в неделю (признак *hours-per-week*)? Сколько людей работают такое количество часов и каков среди них процент зарабатывающих много?**

In [79]:
# your code
data["hours-per-week"].max()

np.int64(99)

In [85]:
hard_working = data[data["hours-per-week"] == data["hours-per-week"].max()]

In [86]:
len(hard_working)

85

In [89]:
hard_working["salary"].value_counts(normalize=True)[">50K"] #:(

np.float64(0.29411764705882354)

**10. Посчитайте среднее время работы (*hours-per-week*) зарабатывающих мало и много (*salary*) для каждой страны (*native-country*).**

In [95]:
# your code
data.groupby(["native-country","salary"]).describe()["hours-per-week"]["mean"]

native-country  salary
?               <=50K     40.164760
                >50K      45.547945
Cambodia        <=50K     41.416667
                >50K      40.000000
Canada          <=50K     37.914634
                            ...
United-States   >50K      45.505369
Vietnam         <=50K     37.193548
                >50K      39.200000
Yugoslavia      <=50K     41.600000
                >50K      49.500000
Name: mean, Length: 82, dtype: float64

**11.Сгруппируйте людей по возрастным группам *young*, *adult*, *retiree*, где:**
* *young* соответствует 16-35 лет
* *adult* - 35-70 лет
* *retiree* - 70-100 лет

**Проставьте название соответсвтуещей группы для каждого человека в новой колонке AgeGroup**

In [97]:
def age_filter(row):
    return "young" if 16< row["age"] < 35 else ("adult" if 35<= row["age"] < 70 else "retiree")

In [98]:
data["AgeGroup"] = data.apply(age_filter,axis=1)

In [99]:
data["AgeGroup"]

0        adult
1        adult
2        adult
3        adult
4        young
         ...
32556    young
32557    adult
32558    adult
32559    young
32560    adult
Name: AgeGroup, Length: 32561, dtype: object

**12-13. Определите количество зарабатывающих >50K в каждой из возрастных групп (колонка AgeGroup), а также выведите название возрастной группы, в которой чаще зарабатывают больше 50К (>50K)**

In [125]:
salary_age =data.groupby(["salary"])["AgeGroup"].value_counts(normalize=True)
salary_age

salary  AgeGroup
<=50K   young       0.508131
        adult       0.470995
        retiree     0.020874
>50K    adult       0.795817
        young       0.189772
        retiree     0.014411
Name: proportion, dtype: float64

In [126]:
salary_age[">50K"]

AgeGroup
adult      0.795817
young      0.189772
retiree    0.014411
Name: proportion, dtype: float64

In [127]:
salary_age[">50K"].idxmax()

'adult'

**14. Сгруппируйте людей по типу занятости (колонка occupation) и определите количество людей в каждой группе. После чего напишите функциюю фильтрации filter_func, которая будет возвращать только те группы, в которых средний возраст (колонка age) не больше 40 и в которых все работники отрабатывают более 5 часов в неделю (колонка hours-per-week)**

In [132]:
# your code
data.groupby(["occupation"]).size()

occupation
?                    1843
Adm-clerical         3770
Armed-Forces            9
Craft-repair         4099
Exec-managerial      4066
Farming-fishing       994
Handlers-cleaners    1370
Machine-op-inspct    2002
Other-service        3295
Priv-house-serv       149
Prof-specialty       4140
Protective-serv       649
Sales                3650
Tech-support          928
Transport-moving     1597
dtype: int64

In [163]:
df1 = data[["age","occupation"]].groupby(["occupation"]).mean("age")<=40

In [160]:
df2 = data.groupby(["occupation"])["hours-per-week"].min()>5

In [185]:
df = pd.concat([df1,df2],axis=1)
df = df["age"] & df["hours-per-week"]
df[df==True].index.values

array(['Armed-Forces'], dtype=object)

In [186]:
def filter_func(data):
    df1 = data[["age","occupation"]].groupby(["occupation"]).mean("age")<=40
    df2 = data.groupby(["occupation"])["hours-per-week"].min()>5
    df = pd.concat([df1,df2],axis=1)
    df = df["age"] & df["hours-per-week"]
    return df[df==True].index.values

In [187]:
filter_func(data)

array(['Armed-Forces'], dtype=object)